apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llm
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: llm
    security.opendatahub.io/enable-auth: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: caikit
      name: ''
      resources:
        limits:
          cpu: '1'
          memory: 2Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 1Gi
          nvidia.com/gpu: '1'
      runtime: llm
      storage:
        key: aws-connection-minio-data-connection
        path: caikit/
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule