apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-tgis-runtime-grpc
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
spec:
  multiModel: true
  supportedModelFormats:
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      command: ["text-generation-launcher"]
      args: ["--model-name=/mnt/models/artifacts/"]
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
    - name: transformer-container
      image: quay.io/rh-ee-mmisiura/caikit-tgis-serving:caiki_nlp_0.5.9
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
        - name: RUNTIME_GRPC_ENABLED
          value: "false"
        - name: RUNTIME_HTTP_ENABLED
          value: "true"
      ports:
        - containerPort: 8080
          name: h2c
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - readiness
        initialDelaySeconds: 5 # might require larger values for large models
      livenessProbe:
        exec:
          command:
            - python
            - -m
            - caikit_health_probe
            - liveness
        initialDelaySeconds: 5