apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llm
  labels:
    opendatahub.io/dashboard: 'true'
    protocol: "grpconly"
  annotations:
    openshift.io/display-name: llm
    security.opendatahub.io/enable-auth: 'false'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: tgis-runtime-grpc
      storage:
        key: aws-connection-minio-data-connection
        path: flan-t5-small
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule