apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: tgis-runtime-grpc
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
spec:
  multiModel: true
  supportedModelFormats:
    - autoSelect: true
      name: pytorch
  containers:
    - name: kserve-container
      image: quay.io/opendatahub/text-generation-inference:stable
      command: ["text-generation-launcher"]
      args:
        - "--model-name=/mnt/models/"
        - "--port=3000"
        - "--grpc-port=8033"
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp/transformers_cache
      readinessProbe: # Use exec probes instad of httpGet since the probes' port gets rewritten to the containerPort
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
      livenessProbe:
        exec:
          command:
            - curl
            - localhost:3000/health
        initialDelaySeconds: 5
        # periodSeconds: 5
      ports:
        - containerPort: 8033
          name: h2c
          protocol: TCP